---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  #  - bundle config set without 'system_tests'
script:
  - 'bundle exec rake $CHECK'
rvm:
  - 2.4.1
env:
  global:
    - PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      bundler_args:
      dist: trusty
      env: PLATFORM=centos:el_puppet6
      rvm: 2.4.1
      script:
        #- bundle exec rake 'litmus:provision[docker, litmusimage/centos:7]'
        - bundle exec rake 'litmus:provision_list[travis_el]'
        - bundle exec rake litmus:install_agent
        - bundle exec rake litmus:install_module
        - travis_wait 60 bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.1
branches:
  only:
    - master
    - /^feature/
    - /^v\d/
    - release
    - development
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = no"
